### ISSUE TITLE
data issue

### ISSUE THREAD

**Issue by dragonflyby666** [Cyril-Mergny/Plume_Detection#1]
Could I ask you some of key elements (restericted by the github uploading rule) that used to train the model?
Thanks  again！

**Comment by cmergny** [comment]
Unfortunately this is an old project (5 years old) and can't find these data files anymore. I have answered to your email, thank you for you interest :)

**Comment by dragonflyby666** [comment]
Thank you very much for your prompt response to my inquiry.And Thank you once again for your assistance and for the valuable contributions you have made through your research！
